### ISSUE TITLE
Let's open source!

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/robrt#9]
I'm considering open sourcing this right now, in it's current state.

Sure, there are security issues, but keeping this hidden isn't the way to deal with that.  Also, someone might actually help me fix some of these issues, either to use Robrt or simply to prove a point.  Not to mention that those issues really do need to be fixed before the release of the online BRTPG, so there's no way around them...

And sure, there are other things I would like to change and/or improve before calling this stable, but I see no reason why I can't do that in public.  Indeed, by having it visible to everyone I'm _more_ likely to keep working on this.

---

@aszasz I'm sure you don't have any objections, but do let me know your thoughts about this...

Also, I would like your opinion on the license: the usual BSD 2-clause (or 3-clause), the MIT license or GPL?

**Comment by jonasmalacofilho** [comment]
The missing bits of documentation will be filled in as improvements are made.

**Comment by aszasz** [comment]
:+1: :grimacing: :grin:
